#!/usr/bin/env bash
# Give the hermes agent locked-down access to the media-add CLI.
#
#   sudo bash ~/.dotfiles/linux/media/hermes-media-setup.sh
#
# Creates a dedicated `mediabot` user whose ONLY capability is running media-add
# via an SSH forced-command (no shell, no port/agent forwarding, no pty). The
# agent reaches it like any other target:
#     ssh -F /opt/hermes-ssh/config media 'series search Severance'
#
# Reuses the main agent key (hermes_id_ed25519) — the forced-command, not the
# key, is the security boundary: through the `media` host that key can do
# nothing but media-add. Idempotent; append-only on shared files.
set -euo pipefail

[ "$(id -u)" -eq 0 ] || { echo "run as root: sudo bash $0"; exit 1; }

OP="${SUDO_USER:-max}"
OP_HOME="/home/$OP"
REPO="$OP_HOME/.dotfiles/linux/media"
MEDIA_ENV_SRC="$REPO/.env"
PUB="${HERMES_PUBKEY:-$OP_HOME/.hermes/ssh/hermes_id_ed25519.pub}"
U="mediabot"

[ -f "$MEDIA_ENV_SRC" ] || { echo "missing $MEDIA_ENV_SRC (run media setup first)"; exit 1; }
[ -f "$PUB" ] || { echo "missing hermes pubkey: $PUB"; exit 1; }

# 1. Dedicated, shell-restricted user (forced-command makes the shell moot).
if ! id "$U" >/dev/null 2>&1; then
    useradd --system --create-home --shell /bin/bash "$U"
    echo "created user $U"
fi
U_HOME="$(getent passwd "$U" | cut -d: -f6)"

# 2. Install the CLI + dispatcher system-wide (on $U's PATH, root-owned).
install -m 0755 "$REPO/media-add" /usr/local/bin/media-add
install -m 0755 "$REPO/hermes-media-dispatch" /usr/local/bin/hermes-media-dispatch
echo "installed /usr/local/bin/{media-add,hermes-media-dispatch}"

# 3. API keys readable by mediabot only (not the operator's whole .env).
umask 027
{
    echo "# Generated by hermes-media-setup.sh — *arr API keys for media-add."
    grep -E '^(SONARR|RADARR)_API_KEY=' "$MEDIA_ENV_SRC"
} > /etc/media-add.env
chown "root:$U" /etc/media-add.env
chmod 0640 /etc/media-add.env
echo "wrote /etc/media-add.env (root:$U 0640)"

# 4. authorized_keys with the forced-command (append-only, idempotent).
install -d -m 0700 -o "$U" -g "$U" "$U_HOME/.ssh"
akf="$U_HOME/.ssh/authorized_keys"
touch "$akf"
opts='command="/usr/local/bin/hermes-media-dispatch",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty'
key="$(cat "$PUB")"
line="$opts $key"
if ! grep -qF "$key" "$akf"; then
    printf '%s\n' "$line" >> "$akf"
    echo "authorized hermes key in $akf (forced-command)"
else
    echo "hermes key already authorized in $akf"
fi
chown "$U:$U" "$akf"; chmod 0600 "$akf"

# 5. Add a `media` entry to the hermes SSH inventory (best-effort, idempotent).
add_inventory() {
    local cfg="$1"
    [ -f "$cfg" ] || return 0
    grep -qE '^Host media$' "$cfg" && { echo "inventory $cfg: media already present"; return 0; }
    cat >> "$cfg" <<EOF

# --- media stack control (forced-command: media-add only) ---
Host media
    HostName 172.17.0.1
    User $U
    IdentityFile /opt/hermes-ssh/hermes_id_ed25519
EOF
    echo "added 'media' host to $cfg"
}
add_inventory /opt/hermes-ssh/config
add_inventory "$OP_HOME/.hermes/ssh/config"

echo
echo "Done. Test from the hermes side:"
echo "  ssh -F /opt/hermes-ssh/config media 'series search Severance'"
echo "  ssh -F /opt/hermes-ssh/config media 'status'"
echo
echo "If you keep a /media skill for the agent, install it with:"
echo "  sudo bash $REPO/hermes-media-skill.sh"
