#!/usr/bin/env bash
# Give the hermes agent locked-down access to the media-add CLI.
#
#   sudo bash ~/.dotfiles/linux/media/hermes-media-setup.sh
#
# Creates a dedicated `mediabot` user whose ONLY capability is running media-add
# via an SSH forced-command (no shell, no port/agent forwarding, no pty). The
# agent reaches it like any other target:
#     ssh -F /opt/hermes-ssh/config media 'series search Severance'
#
# Reuses the main agent key (hermes_id_ed25519) — the forced-command, not the
# key, is the security boundary: through the `media` host that key can do
# nothing but media-add. Idempotent; append-only on shared files.
set -euo pipefail

[ "$(id -u)" -eq 0 ] || { echo "run as root: sudo bash $0"; exit 1; }

OP="${SUDO_USER:-max}"
OP_HOME="/home/$OP"
REPO="$OP_HOME/.dotfiles/linux/media"
MEDIA_ENV_SRC="$REPO/.env"
PUB="${HERMES_PUBKEY:-$OP_HOME/.hermes/ssh/hermes_id_ed25519.pub}"
U="mediabot"

[ -f "$MEDIA_ENV_SRC" ] || { echo "missing $MEDIA_ENV_SRC (run media setup first)"; exit 1; }
[ -f "$PUB" ] || { echo "missing hermes pubkey: $PUB"; exit 1; }

# 1. Dedicated, shell-restricted user (forced-command makes the shell moot).
if ! id "$U" >/dev/null 2>&1; then
    useradd --system --create-home --shell /bin/bash "$U"
    echo "created user $U"
fi
U_HOME="$(getent passwd "$U" | cut -d: -f6)"

# 2. Install the CLI + dispatcher system-wide (on $U's PATH, root-owned).
install -m 0755 "$REPO/media-add" /usr/local/bin/media-add
install -m 0755 "$REPO/hermes-media-dispatch" /usr/local/bin/hermes-media-dispatch
echo "installed /usr/local/bin/{media-add,hermes-media-dispatch}"

# 3. API keys readable by mediabot only (not the operator's whole .env).
umask 027
{
    echo "# Generated by hermes-media-setup.sh — *arr API keys for media-add."
    grep -E '^(SONARR|RADARR|LIDARR)_API_KEY=' "$MEDIA_ENV_SRC"
} > /etc/media-add.env
chown "root:$U" /etc/media-add.env
chmod 0640 /etc/media-add.env
echo "wrote /etc/media-add.env (root:$U 0640)"

# 4. authorized_keys with the forced-command (append-only, idempotent).
install -d -m 0700 -o "$U" -g "$U" "$U_HOME/.ssh"
akf="$U_HOME/.ssh/authorized_keys"
touch "$akf"
opts='command="/usr/local/bin/hermes-media-dispatch",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty'
key="$(cat "$PUB")"
line="$opts $key"
if ! grep -qF "$key" "$akf"; then
    printf '%s\n' "$line" >> "$akf"
    echo "authorized hermes key in $akf (forced-command)"
else
    echo "hermes key already authorized in $akf"
fi
chown "$U:$U" "$akf"; chmod 0600 "$akf"

# 5. Add a `media` entry to the GATEWAY's SSH inventory. The gateway runs as the
# hermes service user and mounts ITS OWN ~/.hermes/ssh as /opt/hermes-ssh inside
# the sandbox (see docker_volumes in the hermes config) — so the entry and key
# must live there, not in the operator's ~/.hermes/ssh.
HERMES_USER="${HERMES_USER:-hermes}"
gw_ssh_dir=""
if id "$HERMES_USER" >/dev/null 2>&1; then
    # Read the mount source for /opt/hermes-ssh straight from the gateway config.
    gw_ssh_dir="$(runuser -u "$HERMES_USER" -- bash -lc \
        'grep -oP "^[[:space:]]*-[[:space:]]*\K[^:]+(?=:/opt/hermes-ssh:ro)" "$(hermes config path)" 2>/dev/null' \
        2>/dev/null | head -1)"
    [ -n "$gw_ssh_dir" ] || gw_ssh_dir="/home/$HERMES_USER/.hermes/ssh"
fi

# HostName the agent's rootless sandbox can actually reach. NOT 172.17.0.1 —
# that's the rootless docker bridge gateway (no sshd there → connection
# refused). Prefer the stable Tailscale IP; fall back to the primary LAN IP.
host_ip="$(tailscale ip -4 2>/dev/null | head -1)"
[ -n "$host_ip" ] || host_ip="$(ip -4 route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+' | head -1)"
[ -n "$host_ip" ] || host_ip="127.0.0.1"

if [ -n "$gw_ssh_dir" ] && [ -d "$gw_ssh_dir" ]; then
    cfg="$gw_ssh_dir/config"
    touch "$cfg"
    if grep -qE '^Host media$' "$cfg"; then
        echo "inventory $cfg: media already present"
    else
        cat >> "$cfg" <<EOF

# --- media stack control (forced-command: media-add only) ---
Host media
    HostName $host_ip
    User $U
    IdentityFile /opt/hermes-ssh/hermes_id_ed25519
EOF
        echo "added 'media' host to $cfg (HostName $host_ip)"
    fi
    # The agent key must exist in the gateway's ssh dir (it usually already does).
    if [ ! -f "$gw_ssh_dir/hermes_id_ed25519" ] && [ -f "$OP_HOME/.hermes/ssh/hermes_id_ed25519" ]; then
        install -m 0600 "$OP_HOME/.hermes/ssh/hermes_id_ed25519" "$gw_ssh_dir/hermes_id_ed25519"
        echo "copied agent key into $gw_ssh_dir"
    fi
    chown -R "$HERMES_USER:$HERMES_USER" "$cfg" "$gw_ssh_dir/hermes_id_ed25519" 2>/dev/null || true
else
    echo "NOTE: gateway ssh dir not found; add the 'media' host to the agent's"
    echo "      inventory manually (HostName 172.17.0.1, User $U, the agent key)."
fi

echo
echo "Done. Direct test (as the operator, bypassing the agent inventory):"
echo "  ssh -i $OP_HOME/.hermes/ssh/hermes_id_ed25519 -o IdentitiesOnly=yes \\"
echo "      ${U}@localhost 'series search Severance'"
echo
echo "Then test through the agent on Telegram (it resolves the 'media' host):"
echo "  \"buscá la serie Severance en el media server\""
echo
echo "Install the /media agent skill with:"
echo "  sudo bash $REPO/hermes-media-skill.sh"
