#!/usr/bin/env bash

path="${1:-$PWD}"

if common_dir="$(git -C "$path" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"; then
    case "$common_dir" in
        */.git) basename "$(dirname "$common_dir")" ;;
        *) basename "$common_dir" ;;
    esac
else
    basename "$path"
fi
